### ISSUE TITLE
Scaffolding for plugins

### ISSUE THREAD

**Issue by kangax** [babel/minify#307]
Adding new plugins involves [quite a bit of boilerplate](https://github.com/babel/babili/pull/286/files). What if we create a script to do minimal scaffolding:

1. Create new dir
2. Add .npmignore
3. Add README.md
4. Add src file w. minimal code
5. Add test file w. minimal code
6. Add plugin name to preset
etc.

**Comment by boopathi** [comment]
I was working on point 6. Will work on that again.

**Comment by boopathi** [comment]
Closing due to low priority. Can reopen if necessary. New plugins addition isn't frequent anymore.

**Comment by j-f1** [comment]
A way to fix this for now would be to create a template directory that can be copied and filled out with the actual plugin code.
