### ISSUE TITLE
babili is removing function arguments in scope of eval call

### ISSUE THREAD

**Issue by targos** [babel/minify#366]
The following code:

```js
'use strict';
function myEval(code, _var_) {
  eval(code);
}
myEval('console.log(_var_)', 'myValue');
```

Is transformed to:
```js
'use strict';function myEval(code){eval(code)}myEval('console.log(_var_)','myValue');
```

Which does not work.

I'm using `babel-preset-babili` v0.0.9. The bug was not present in v0.0.5. I suppose it was introduced in https://github.com/babel/babili/commit/10b114f26533a58f66bb8a8ae90335c7353d1085.

**Comment by kangax** [comment]
I'm surprised this didn't break our eval tests.

**Comment by kangax** [comment]
Oh, we only test for mangling, not argument removal — https://github.com/babel/babili/blob/b8bac37d02c471e2c0f7a845b8afce572870092c/packages/babel-plugin-minify-mangle-names/__tests__/mangle-names-test.js#L493 🙈

**Comment by targos** [comment]
I still get the same output with babili 0.0.11 which includes #371. Do I need to set an option?

**Comment by targos** [comment]
Unless I'm mistaken, can this be reopen, please?

**Comment by targos** [comment]
Hello. Can you please open again? The issue is back in latest babili version [example](https://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=env%2Creact&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code_lz=OQVwzgpgBGAuBOBLAxrYBuAUAMxAO1UQHs8oBbATwFEA3AQwBsAKZIgEwgBooB9e-HgEooAb0xQoEes1YdBWAL6ZKtRk2Cs8YIgwgA6BkQDmTPnQGDg3YJQBqjEBGDygA).

**Comment by boopathi** [comment]
Interesting. I tried it with the master branch which was released a few days ago and this bug is not present. The repl is outdated I suppose - I'll check that.

**Comment by j-f1** [comment]
It looks like the REPL is running Babili `0.0.9` (run `Babili.version` in the DevTools), and the latest is `0.1.4`

**Comment by targos** [comment]
I checked with the latest release on my app. Maybe this testcase is too simple now. I will check again.

**Comment by targos** [comment]
@boopathi here is the result I get with `babel-preset-babili@0.1.4`:

```
$ cat test.js
'use strict';
function myEval(code, _var_) {
  eval(code);
}
myEval('console.log(_var_)', 'myValue');

$ babel test.js --presets babili
'use strict';function myEval(a,b){eval(a)}myEval('console.log(_var_)','myValue');

```
