### ISSUE TITLE
dead code elimination and mangling are not correct

### ISSUE THREAD

**Issue by TrySound** [babel/minify#404]
resetTriggers in this file is removed in the first case and renamed only in declaration in the second.
https://github.com/sdecima/javascript-detect-element-resize/blob/master/detect-element-resize.js

**Comment by boopathi** [comment]
Do you have a minimal repro snippet? It'll be easy to spot the error.

**Comment by TrySound** [comment]
Yep. Here it is

```js
if (!window.condition) {
	function resetTriggers(element) {
		console.log(element);
	}
}

window.addResizeListener = element => resetTriggers(element);
```

A bit weird case but quite real.

**Comment by boopathi** [comment]
Also to note that in strict mode, function declarations are hoisted to the block (`let` binding). So this bug is valid only for non strict mode.

eg: http://jsbin.com/leyemoloda/edit?html,console

**Comment by TrySound** [comment]
Oh, nice. Didn't know. Then I have no questions.

**Comment by boopathi** [comment]
This hasn't come up again. Will close this issue. Will open again if someone depends on non-strict mode.
