### ISSUE TITLE
Some for loops cause incorrect output

### ISSUE THREAD

**Issue by cpetrov** [babel/minify#430]
Using `let` in the initialization part of the `for` loop used in the function `foo()` leads to incorrect output.

**Input:**
```js
function foo() {
  let len = 0;
  for (let i = 0; i < 2; i++) {}
  return len;
}
```

**Output:**
```js
"use strict";function foo(){for(var b=0;2>b;b++);return a}
```

The returned variable `a` is not defined. The function `foo()` must always return `0`.

Demo: `https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=function foo() {  let len %3D 0%3B  for (let i %3D 0%3B i < 2%3B i%2B%2B) {}  return len%3B}`

**Comment by vigneshshanmugam** [comment]
Doesn't seem like babili bug. The `es2015` transformation is replacing 0 with identifier `a`

/cc @hzoo

**Comment by boopathi** [comment]
Another let to var binding issue. 

Related #412, https://github.com/babel/babel/issues/4818
