### ISSUE TITLE
export async function -> undefined if there is an import in file

### ISSUE THREAD

**Issue by miqmago** [babel/minify#449]
This is a very specific case: When `export async function(...) { ... }` and there is at least one `import` in the file, the exported function get's `undefined`. See example here: https://github.com/miqmago/import-async-undefined (run `npm i && npm start`)

**testController1.js**
```js
import global from './global'; // If this import is removed, then all works fine

export async function testFunc1(req, res, next) {
}

export const testFunc2 = async (req, res, next) => {
};
```

**testRouter.js**
```js
import { testFunc1 } from './testController1.js' // testFunc1 is undefined
```

**Comment by JamieDixon** [comment]
I'm seeing the same behaviour in our app.

**Comment by boopathi** [comment]
I'm not sure which PR fixed this issue, this doesn't happen in current master.
