### ISSUE TITLE
redefine variable when converting let to var

### ISSUE THREAD

**Issue by guoerwei** [babel/minify#477]
```javascript
{
  let count = 0;
  setInterval(() => {
    console.log('first tick: ', ++count);
  }, 200);
}
{
  let count = 0;
  setInterval(() => {
    console.log('second tick: ', ++count);
  }, 300);
}
```

with babili, will simply converts to

```javascript
{
  var a = 0;
  setInterval(function() {
    console.log('first tick: ', ++a)
  }, 200)
}
{
  var a = 0;
  setInterval(function() {
    console.log('second tick: ', ++a)
  }, 300)
}
```

and getting variable redefined

**Comment by hzoo** [comment]
Hey @guoerwei! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
