### ISSUE TITLE
Weird mangle error

### ISSUE THREAD

**Issue by dhcmrlchtdj** [babel/minify#554]
#### problem

Mangle is incorrect.

#### example

```javascript
// input
function example() {
    let mangleError = [];
    let i = 10;
    while (--i) mangleError.push(i);
    return mangleError;
}

// output
"use strict";function example(){for(var a=[],b=10;--b;)a.push(b);return mangleError}
```

```sh
$ echo \
"function example() {
    let mangleError = [];
    let i = 10;
    while (--i) mangleError.push(i);
    return mangleError;
}" | ./node_modules/.bin/babel --presets=es2015,babili
```

#### package version

- babel-preset-es2015@6.24.1
- babel-preset-babili@0.1.2

---

update:
I found it's caused by `--plugins=minify-simplify,transform-merge-sibling-variables,minify-mangle-names,transform-es2015-block-scoping`

**Comment by boopathi** [comment]
Thanks. This is only when used with `es2015-block-scoping` . 

+ [Similar issues](https://github.com/babel/babili/issues?q=is%3Aissue+is%3Aopen+label%3A%22with+es2015%22)
