### ISSUE TITLE
transform-inline-environment-variables fails to find .KEY but works with ["KEY"]

### ISSUE THREAD

**Issue by alexkrolick** [babel/minify#569]
```sh
export MY_ENV_VAR=foo
react-native start
react-native run-android
```

```js
const myEnvVar1 = process.env.MY_ENV_VAR    // undefined
const myEnvVar2 = process.env["MY_ENV_VAR"] // foo 
```

Seemingly related: 

https://github.com/babel/babili/blob/a0922fc439003a6039a5e3a20cde982f21f7cf93/packages/babel-plugin-transform-inline-environment-variables/src/index.js

https://github.com/babel/babel/blob/9e2ef0cf9e87b4b829d891d45102c96fca7c2038/packages/babel-types/src/definitions/core.js#L351-L359

https://github.com/babel/babel/blob/943fa8aa7328266892527049c08c161570893373/packages/babel-types/src/converters.js#L6

**Comment by boopathi** [comment]
Thanks. The location of code is spot on. Do you want to send a PR for the same?

**Comment by kball** [comment]
I just attempted to reproduce this in test based on current master and was unable to. I'm new to babel development so entirely possible I did something wrong, but can you confirm if this is still an issue or has been resolved?

**Comment by pauldariye** [comment]
Is this still an issue?
