### ISSUE TITLE
Babili not validating values properly

### ISSUE THREAD

**Issue by Rud156** [babel/minify#581]
If something like this is put through Babili:
```js
let pre = false;
let array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
let randomNumber = Math.floor(Math.random() * 5);
for(let i = 0; i < array.length; i++)
  if(randomNumber === array[i]){
    pre = true;
    break;
  }
if(!pre)
  console.log("Hello");
```

Then it splits out:
```js
"use strict";for(var array=[1,2,3,4,5,6,7,8,9,10],randomNumber=Math.floor(5*Math.random()),i=0;i<array.length;i++)if(randomNumber===array[i]){break}pre||console.log("Hello");
```
The above mentioned code will fail as the variable `pre` is not defined but is used in a `"strict"` environment. There are other ways to implement the above code like using a `return` instead of `break`. But this methods fails. Looks like a BUG

**Comment by vigneshshanmugam** [comment]
es2015 scoping issue.

**Comment by boopathi** [comment]
Similar issues - https://github.com/babel/babili/labels/with%20es2015

**Comment by Rud156** [comment]
Is there any workaround other than changing the code myself?

**Comment by boopathi** [comment]
It should be possible to use `babili` as a separate pass and not use it alongside `preset-es2015`. This bug happens only when using `babili` and `es2015` together. There are tools like [babili-webpack-plugin](https://github.com/wepback-contrib/babili-webpack-plugin) if you're using webpack, gulp-babili if you're using gulp, `rollup-plugin-babili` if you're using rollup, and also you can build your own with other tools as well.

**Comment by Rud156** [comment]
Ok thanks
