### ISSUE TITLE
Exclude `console.error` from babel-plugin-transform-remove-console

### ISSUE THREAD

**Issue by nerdmed** [babel/minify#598]
Is there a way to exclude the removal of `console.error` from the `babel-plugin-transform-remove-console` plugin. This would be really helpful, we override console.error in production to track errors to our tools.

**Comment by j-f1** [comment]
There could be a set of boolean options for each `console` method.

**Comment by nerdmed** [comment]
that would be great for me some option like this would be perfect:

```json
{
  "exclude": ["error"]
}
```
could also contain multiple values
```json
{
  "exclude": ["error", "warn", "trace", "info"]
}
```

**Comment by xtuc** [comment]
Closing this since https://github.com/babel/minify/pull/661 has been merged.

**Comment by sponia-joker** [comment]
it didn't work in server render with options

**Comment by xtuc** [comment]
@sponia-joker could you please open a new issue with more context about that? I might be just an issue with the version you're using I think.

**Comment by chikara-chan** [comment]
At latest release version, this feature doesn't exist.

**Comment by chikara-chan** [comment]
@xtuc have you forgot to publish it?
