### ISSUE TITLE
Deadcode erroneously mangling names wrt eval?

### ISSUE THREAD

**Issue by akx** [babel/minify#605]
When using the 'cheap-module-eval-source-map' devtool mode, Webpack 3.x (also 2.x) generates code like

```javascript
webpackJsonp([0],[
/* 0 */,
/* 1 */,
/* 2 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
eval("\n\nvar global = __webpack_require__(13),\n    core = __webpack_require__(113),\n    hide = __webpack_require__(33),\n    redefine = __webpack_require__(53),\n ...");
```

When using Webpack's Babili plugin (`new BabiliPlugin()`, i.e. passing the code through to `babel-preset-babili@0.1.4`), this gets mangled to

```javascript
webpackJsonp([0],[,,function(c,e,t){"use strict";eval("\n\nvar global = __webpack_require__(13),\n    core = __webpack_require__(113),\n    hide = __webpack_require__(33),\n    redefine = __webpack_require__(53), ...");
``` 

which naturally doesn't work due to the parameters used by the `eval` code being renamed. :crying_cat_face:

Curiously enough, though, setting `{deadcode: false}` (_not_ `mangle`, as one might expect), fixes this! With `new BabiliPlugin({deadcode: false})`, the generated code looks like

```javascript
webpackJsonp([0],[,,function(module,exports,__webpack_require__){"use strict";eval("\n\nvar global = __webpack_require__(13),\n    core = __webpack_require__(113),\n    hide = __webpack_require__(33),\n    redefine = __webpack_require__(53), ...");
```

which does work.

I know it's something of an edge case to have devtools enabled in babilified builds (and in fact it was a mistake on my side to begin with), but this still smells like a bug.

For those searching for this issue and how to solve it, the exception is:
> Uncaught ReferenceError: `__webpack_require__` is not defined at eval

**Comment by boopathi** [comment]
similar issue - https://github.com/babel/babili/issues/366

**Comment by akx** [comment]
Similar, yes, but the variables don't get dropped, they get renamed.

**Comment by stefanb2** [comment]
IMHO probably related issue:

 babel-minify dead code elimination breaks code that uses https://github.com/thenables/thenify, e.g. through dependency chain `koa-send` -> `mz` -> `thenify-all` -> `thenify`. I get the following error message from my code:

```
  koa-send send "/application-main.html" {"root":"/.../static","index":"index.html"} +0ms

  ReferenceError: createCallback is not defined
      at eval (eval at n.withCallback (/.../server.js:296:35169), <anonymous>:11:19)
      at new Promise (<anonymous>)
      at Object.eval [as stat] (eval at n.withCallback (/.../server.js:296:35169), <anonymous>:10:8)
      at t.exports (/.../server.js:203:66675)
      at <anonymous>
```

This is caused by `function createCallback()` being renamed while the original name is used kept in `eval()`: https://github.com/thenables/thenify/blob/aa21cfb64f47238c764d258d0faf7366a8487e36/index.js#L76
