### ISSUE TITLE
constant-folding template strings

### ISSUE THREAD

**Issue by mariusGundersen** [babel/minify#612]
There is a bug in the [babel-plugin-minify-constant-folding](https://github.com/babel/babili/tree/master/packages/babel-plugin-minify-constant-folding) package where it incorrectly inlines template strings. Here is a simple example:

```
const a = ["a", "b"].join(' ');
// -> const a="a b";


const b = [`a${a}`, `b${a}`].join(' ');
// -> const b=" ";
```

In the second example it should keep the interpolation and produce a template string, but it does not, instead returning just an empty string. The result is broken code.

**Comment by vigneshshanmugam** [comment]
@mariusGundersen Thanks for creating the issue, #613 should fix this

**Comment by mgol** [comment]
This has just hit me in production. A very simple complete test case:
```js
const a = 'a';
console.log([`${ a }b`, 'c',].join(''));
```
transpiles to:
```js
const a='a';console.log('c');
```
instead of the expected:
```js
const a='a';console.log(`${ a }bc`);
```
or:
```js
console.log('abc');
```

Perhaps the PR should include a test like that.

**Comment by lydell** [comment]
Could this please be released to npm? @boopathi?
