### ISSUE TITLE
Resolve property access when possible

### ISSUE THREAD

**Issue by CapacitorSet** [babel/minify#618]
I'm trying to deobfuscate some code which contains structures like these:

```
var letter = {
    foo: (a, b, c) => String["fromChar" + b](c),
    bar: "unused"
}.foo(null, "Code", 97)
```

It seems that Babili is unable to resolve this property access, even though it could be done with no side effects (unlike eg. `{bar: functionCallHere()}`). It would be great if it could do this.

**Comment by boopathi** [comment]
Related #336 #344

**Comment by boopathi** [comment]
Closing this as duplicate.
