### ISSUE TITLE
Some of the plugin in this preset delete array reverse call

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/minify#628]
Babili deletes array reverse call (and probably something else as well)
```bash
npm install babel-preset-babili
echo '[...a].reverse()' | babel --presets=babili
```

And the result is
```js
[...a]
```
`reverse()` disappears for no reasons

**Comment by j-f1** [comment]
Looks like I need to exclude array literals with spreads from most of the array methods.

**Comment by yuri-karadzhov** [comment]
Seems like it is plugin ```babel-plugin-minify-constant-folding``` that cause the problem
```bash
echo 'export const b = a => [...a].reverse()' | babel --plugins=babel-plugin-minify-constant-folding
# export const b = a => [...a];
```

**Comment by yuri-karadzhov** [comment]
babel-plugin-minify-constant-folding@0.1.1 does not have this problem
