### ISSUE TITLE
Unhandled param in try-catch results in re-declaring const

### ISSUE THREAD

**Issue by keegan-lillo** [babel/minify#635]
#### Input Code
```bash
$ babili test.js
```

```js
try {
  throw new Error('foo')
} catch (er) {
  const st = window.location
  console.log(st)
}
```

#### Actual Output

```js
try{throw new Error('foo')}catch(a){const a=window.location;console.log(a)}
```

results in:

`Uncaught SyntaxError: Identifier 'a' has already been declared`

#### Expected Output

```js
try{throw new Error('foo')}catch(a){const b=window.location;console.log(b)}
```

#### Details
Looks like the mangle plugin does bad things when there is an unhandled error param in try-catch blocks. This becomes an issue when using the `const` keyword 

https://github.com/npm/node-tar/blob/9440c435711a32f5de4d1a2ddf5bb58da766c06c/lib/mkdir.js#L103 is a live example of this occurring.

**Comment by boopathi** [comment]
Interesting. Babel's scope sends this as 

```js
try {
  bar();
} catch (err) {  // <-- errPath.scope = CatchClause; uid = 1
  const foo = 1; // <-- fooPath.scope = BlockStatement; uid = 2
}
```

i.e. err and foo are in different scopes(or in babel, they are in different path.scope). Though, the parser finds this as an early error and exits - [Example](http://astexplorer.net/#/gist/9c88c2f015db3ff6fca5ae4f4935aee9/42ddc3095fd4002217bb51419e3d036e593507e9)

**Comment by boopathi** [comment]
This is fixed in babel. with babili + babel 7 this will not happen.
