### ISSUE TITLE
Running CLI when no TTY

### ISSUE THREAD

**Issue by probins** [babel/minify#666]
I'm trying to convert my existing `babel` with preset commands on GitLab Pages CI to the new `minify`, but am running into problems because there's no TTY on the Docker runner the CI uses. I find a [related issue](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2115#note_22926183) which states that 'There is no tty with Gitlab CI'. This means that `process.stdin.isTTY` is always false (see [simple test](https://gitlab.com/probins/testtty/-/jobs/29327772)), and `cli.js` runs `runStdin()` which fails because there are file params.

I can for the moment continue to use `babel`/preset, but I think it would be better if `minify` could handle this situation, perhaps by adding an option to bypass the TTY check if running in this sort of environment?

**Comment by boopathi** [comment]
Would it make sense for a CLI if providing files overrides stdin? Right now the first thing the CLI tries to do is to find if it can read from stdin via `process.stdin.isTTY`. 

What does other CLIs used in CI environments do in this situation?

**Comment by probins** [comment]
yes, I think it would make sense to check files first, then tty, then help. I've not come across this issue before (it took me quite a while to work out the cause), and I'm not sure how widespread it might be.

**Comment by boopathi** [comment]
Thanks! Yeah. I think it'd be least surprising one. Would you like to send a PR for the same?

**Comment by probins** [comment]
I can change the code and do my own tests, and then create a PR based on that. But you probably want to add some tests for this, and I see you use yarn and other things I'm not familiar with. So it's probably more efficient for you (or someone else who's familiar with the project) to make the change rather than me having to spend time familiarising myself with your set-up just for this smallish change. (Not trying to get out of doing things, but ... :-))

**Comment by j-f1** [comment]
@probins Constder his an excuse to learn about Yarn, then. 😄
