### ISSUE TITLE
Minification does not convert variables names properly.

### ISSUE THREAD

**Issue by moimael** [babel/minify#667]
Hi,

I started using babili and I have a piece of code that is improperly minified.

```
      static getIndexes(count, inc) {
        const arr = [];
        for (let i = 0; i < count; i += inc) {
          arr.push(i);
        }
        return arr;
      }
```

becomes this after minification:
```
[{key:'getIndexes',value:function getIndexes(a,b){for(var c=[],d=0;d<a;d+=b)c.push(d);return arr}}
```

As you can see, `arr` is transformed to `c` when declared, but in the return it is still called `arr` which leads to `arr is undefined` error.

**Comment by boopathi** [comment]
Thanks. Duplicate #594
