### ISSUE TITLE
Incorrect minification of array check

### ISSUE THREAD

**Issue by benbrandt** [babel/minify#677]
#### Input Code
This is code in angular-animate:
```js
if (events && events.length) {
  // Remove the transitionend / animationend listener(s)
  element.off(events.join(" "), onAnimationProgress);
}
```

#### Actual Output

```js
Z.length && n.off(Z.join(' '), R);
```

#### Expected Output

```js
Z && Z.length && n.off(Z.join(' '), R);
```

#### Details
Configuration - babel-minify configuration or babelrc
 - Default configuration. Fixed if I turn off `guards` and `simplify`

Whether you used it with other presets/plugins - like es2015 or env
 - Babel config:
```
"babel": {
  "presets": ["talentpair"],
  "plugins": [["angularjs-annotate", { "explicitOnly": false }]]
},
```

Environment: gulp, rollup, webpack, babel-cli, etc...?
- Webpack

**Comment by j-f1** [comment]
I can’t reproduce this [in the REPL](http://babeljs.io/repl/#?babili=true&code_lz=JYMwBAFApgblB2AXAzmAZGssEoHQBsEBzRACwEowBvAKDDAHoGwAlKAWwHs4wypeATgEN4yYImCd4CACaMwI4OyESpssPmDJECKAIjJydLIXY5cnECGhwkyXACtOweBABEYN-QA0YKQEF4JRVJeAAFAU4iAShkQwBuGgBfGiA). Can you find a code example that reproduces this behavior by itself?

**Comment by benbrandt** [comment]
Ok here's a gist with the full file where it's happening again:
https://gist.github.com/benbrandt/34561643335f1d7442d53272a9080512

Where the line occurs in angular-animate: https://gist.github.com/benbrandt/34561643335f1d7442d53272a9080512#file-angular-animate-js-L1267

I then ran the minified version through prettier for easier readability, and here the issue is again: https://gist.github.com/benbrandt/34561643335f1d7442d53272a9080512#file-minified-and-prettier-version-js-L996

The original minified version is included as well. I ran it through the REPL, but the url was too long to share

**Comment by boopathi** [comment]
If I'm looking at it correctly, the var `events` is declared once [here](https://gist.github.com/benbrandt/34561643335f1d7442d53272a9080512#file-angular-animate-js-L990) as `var events = []` and is NEVER re-assigned. What the minifier does is correct here.

But if you've drilled down the bug to this location, did this affect you at runtime? If so, what runtime error did you get and where did you get the runtime error?

**Comment by benbrandt** [comment]
Yes it happens at runtime. This is the error I get:
```
angular.js:14701 TypeError: Cannot read property 'length' of undefined
    at y (angular-animate.js:1269)
    at T (angular-animate.js:1305)
    at angular-animate.js:977
    at Object.translate3d (angular-material.js:7335)
    at s.C3Pe.s.animateClose (angular-material.js:18193)
    at angular-material.js:17052
    at r.M [as _$q] (angular.js:17350)
    at r.C3Pe.r._animateClose (angular-material.js:17047)
    at angular-material.js:16447
    at r.M [as _$q] (angular.js:17350)
    at r.C3Pe.r.hide (angular-material.js:16419)
    at angular-material.js:16243
    at r (angular.js:17051)
    at angular.js:17095
    at c.$digest (angular.js:18233)
    at angular-material.js:1730
    at angular.js:20440
    at o (angular.js:6362)
    at angular.js:6643 "Possibly unhandled rejection: {}"
```
When I click on `at y (angular-animate.js:1269)` the sourcemaps take me right to that spot in the code:
```
if (events && events.length) {
  // Remove the transitionend / animationend listener(s)
  element.off(events.join(' '), onAnimationProgress);
}
```

**Comment by boopathi** [comment]
Interesting. But I can't see anywhere where events could be `undefined`. There is no reassignment of events. 

Also, source maps could be wrong. Can you confirm without source maps if this is the `events` variable or something else?

**Comment by benbrandt** [comment]
I can do my best. Any suggestions to make sure I'm looking at this correctly? 

Also, I noticed that events looks like it is called `Nt` , but `Nt` isn't assigned a value until line 1140 (https://gist.github.com/benbrandt/34561643335f1d7442d53272a9080512#file-minified-and-prettier-version-js-L1140) but where the error is being throw is much earlier. Is it possible the variable isn't initialized yet when the function is being run?

Could be way off, but figured I'd ask. Thanks!
