### ISSUE TITLE
Interpolated strings get removed from array joins

### ISSUE THREAD

**Issue by ysulyma** [babel/minify#680]
#### Input Code

```js
const x = ["1 + 1 is", `${1+1}`].join(' ');
```

#### Actual Output

```js
const x="1 + 1 is ";
```

#### Expected Output

```js
const x="1 + 1 is 2";
```

**Comment by vigneshshanmugam** [comment]
Its already fixed by this PR https://github.com/babel/minify/pull/613

We will release a new version soon.
