### ISSUE TITLE
Babel doesn't minify or transpile. Also, it doesn't echo any Errors.

### ISSUE THREAD

**Issue by Behzad-Hatamikia** [babel/minify#688]
Hi everyone
I've been stuck for around two days now with my webpack and babel configuration and while I've been able to fix some of my issues with webpack, I can't seem to be able to make babel and its minify plugin to work. It produces a huge js file that doesn't seem to be minified.
is there anything that I'm missing?

my devDependecies for babel are as follows:

> "babel-core": "^6.26.0",
>     "babel-loader": "^7.1.2",
>     "babel-minify": "^0.2.0",
>     "babel-plugin-react-transform": "^3.0.0",
>     "babel-preset-es2015": "^6.24.1",
>     "babel-preset-minify": "^0.2.0",
>     "babel-preset-react": "^6.24.1",
> "react-transform-hmr": "^1.0.4",

my webpack config:

> module: {
>       rules: [
>         {
>           test: /\.js$/,
>           exclude: /node_modules/,
>           use: "babel-loader"
>         },

and my .babelrc file:

> {
	"presets": [
		"es2015",
		"react"
	],
	"env": {
		"production": {
			"presets": [
				"minify"
			],
			"comments": false
		},
		"development": {
			"plugins": [
				[
					"react-transform",
					{
						"transforms": [
							{
								"transform": "react-transform-hmr",
								// if you use React Native, pass "react-native" instead:
								"imports": [
									"react"
								],
								// this is important for Webpack HMR:
								"locals": [
									"module"
								]
							}
						]
						// note: you can put more transforms into array
						// this is just one of them!
					}
				]
			]
		}
	}
}

and my production script in package.json is:
`"prod": "rimraf ./dist/* && NODE_ENV=production BABEL_ENV=production webpack --progress"`

Thanks in advance

**Comment by xtuc** [comment]
Did you fix your issue?

**Comment by Behzad-Hatamikia** [comment]
Yeah I figured there was no problem with the babili and I infact needed
 uglifyjs to minify the whole file after its been minified with babili.
Thanks anyway.
