### ISSUE TITLE
Evaluate option ruins template literals

### ISSUE THREAD

**Issue by Beaglefoot** [babel/minify#699]
**Input:**
```javascript
const str = 'first';
const joined = [`${str}`, 'second'].join(', ');
```

**Output:**
```javascript
const str='first',joined=', second';
```

**Expected:**
```javascript
const str='first',joined='first, second';
```

**Details:**
Without babel-preset-es2015 and with [evaluate](https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-constant-folding) option being active minifier simply skips template literals.

**Comment by boopathi** [comment]
With latest master,

```js
// input
const str = 'first';
const joined = [`${str}`, 'second'].join(', ');

// ------------------------
// output

const str = 'first',
      joined = 'first, second';
```

with and without es2015 preset. Please comment to reopen if the bug still persists in master.
