### ISSUE TITLE
Export renaming maps for mangle

### ISSUE THREAD

**Issue by Protryon** [babel/minify#701]
It would be useful in some situations to know what each renamed variable/function, particularly in the global scope, has been renamed, and export of such a map would be perfect.

**Comment by boopathi** [comment]
I'm not certain this specific information is useful nor is anyone maintaining babel-minify is willing to work on this.

We can fix the sourcemaps first from which you'll be able to extract this information. The issue for the same is here - #629 . It is also tagged as `help-wanted`. Any help will be appreciated. I'm closing this request in favour of #629.
