### ISSUE TITLE
Beta status?

### ISSUE THREAD

**Issue by wearhere** [babel/minify#703]
I am super excited to use this project. It pains me to read posts from the V8 team like [this](https://mathiasbynens.be/notes/async-stack-traces) and [this](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/) encouraging developers to deploy ES2015+ code when honestly it's not possible, absent an ES2015+-capable minifier!

But the "beta" label on this project gives me pause. Can you set any expectations for when the project might exit beta, in terms of a timeline and/or bugs that need to be fixed or features that need to be added?

**Comment by GiancarlosIO** [comment]
same here, in my team we want to use this for real-projects

**Comment by lydell** [comment]
I use this in two production projects. It generally works well, but I've run into one bug one each project where babel-minify partially broke some smaller feature. Luckily, there are workarounds for both problems.

So, in my experience, it is usable in production, but you'll have to reserve a couple hours of debugging why a certain feature only breaks in the production (minified) build of your project some time into the future.

**Comment by boopathi** [comment]
There are a couple of [bugs with es2015-block-scoping](https://github.com/babel/minify/issues?q=is%3Aissue+is%3Aopen+label%3A%22with+es2015%22). That is a major blocker for a stable release. There are other issues with babel-minify without using block-scoping plugin. If you're interested in helping out, feel free to send PRs. Thanks!

**Comment by probins** [comment]
I have always assumed the [1.0 milestone](https://github.com/babel/minify/milestone/4) was the relevant list - though it doesn't have any kind of target date. Is that complete/up-to-date?

**Comment by boopathi** [comment]
New issues were not added to 1.0 milestone. Now, I've added some of the relevant issues for 1.0 to that milestone. I'll try to keep it updated. Unfortunately, I can't set a timeline for 1.0.

Closing this. Follow milestone [1.0](https://github.com/babel/minify/milestone/4) for status.
