### ISSUE TITLE
Incorrect minification of react-with-separator

### ISSUE THREAD

**Issue by LinusU** [babel/minify#726]
I'm running into some wrong minification of code that only happens when using the `es2015` preset together with `minify`.

The main function below gets transpiled to the following (whitespace added by me):

```js
module.exports = function (a) {
  for(var b=React.Children.toArray(a.children), c=1; c<b.length; c+=2)
    b.splice(c,0,createSeparator(a.separator,(c-1)/2));
  return children
};
```

As you can see, the `children` variable gets renamed to `b`, but for some reason is still referred to as `children` in the return statement.

The error only happens if the es2015 preset first converts `const` and `let` into `var`. If I first run the es2015 preset, and then run the minify preset on that output, it also works.

Manually converting `const` and `let` into `var`, and then running with both presets also works.

Setting `"mangle": false` still moves the children declaration into the for-loop, but now works since it's called `children`.

Setting `"mergeVars": false` keeps the declaration of `children` outside of the for-loops, and then correctly renames all `children` into `b`.

#### Input Code

The code is this package: [react-with-separator](https://github.com/LinusU/react-with-separator)

```js
'use strict'

const React = require('react')

function createSeparator (separator, idx) {
  if (typeof separator === 'string') {
    return separator
  }

  return React.cloneElement(separator, { key: `separator-${idx}` })
}

module.exports = function WithSeparator (props) {
  const children = React.Children.toArray(props.children)

  for (let i = 1; i < children.length; i += 2) {
    children.splice(i, 0, createSeparator(props.separator, (i - 1) / 2))
  }

  return children
}
```

#### Actual Output

```text
ReferenceError: Can't find variable: children
```

**Comment by boopathi** [comment]
Can you try with master branch? The issue was fixed recently in https://github.com/babel/minify/pull/713

**Comment by LinusU** [comment]
Hmm, I'm not sure exactly how to do that. I tried adding `"babel-preset-minify": "babel/minify#master"`, but that doesn't seem to work because this repository houses multiple packages. Do you have any guides on how to install this from git?

**Comment by boopathi** [comment]
There are some docs at https://github.com/babel/minify/blob/master/CONTRIBUTING.md on how to build. You can yarn link the package you're testing.

**Comment by LinusU** [comment]
That PR does indeed fix it!

When can we expect a new release?
