### ISSUE TITLE
Add a "keep-unicode-literals" option (still many problems with unicode minimize)

### ISSUE THREAD

**Issue by jogibear9988** [babel/minify#728]
Would it be possible to add a keep unicode literals option?

There are still many errors with unicode literals and minimize.

see:

https://github.com/babel/minify/issues/627
https://github.com/Polymer/polymer-cli/issues/886
https://github.com/Polymer/polymer-cli/issues/633
https://github.com/Polymer/polymer-cli/issues/701

**Comment by boopathi** [comment]
This is fixed in #730

**Comment by jogibear9988** [comment]
i think Polymer/polymer-cli#886 is not yet solved
