### ISSUE TITLE
Create new Release?

### ISSUE THREAD

**Issue by jogibear9988** [babel/minify#731]
With the many new patches applied, is it possible to create a new release?

**Comment by jogibear9988** [comment]
If not, how can I use the current git master of babel-minfy?

I tried npm install https://github.com/babel/minify/tree/master/packages/babel-minify wich did not work

**Comment by jogibear9988** [comment]
Would be good, if https://github.com/babel/minify/issues/732 could be fixed first ;-) (I've created a pull req)

**Comment by xtuc** [comment]
See npm's documentation https://docs.npmjs.com/cli/install

**Comment by jogibear9988** [comment]
I've already looked at. But I didn't find a solution when the Repo contains more than one package...

I got it to work when I fetch the repo vis git, compile it with gulp and then run npm install for every subfolder of packages.

But this is nothing I can do on our build server.

Can you say when a new release is planed?

And maybe you can look at my pull req?
