### ISSUE TITLE
Breaks conditional extends

### ISSUE THREAD

**Issue by johanjisu** [babel/minify#739]
minify breaks code with conditional extends, such as this:

```
export default Target => class Events extends (Target || Base) {

}
```

Minification removes () around Target || Base, which breaks it.

(the code above is used for mixins, Base is an existing class)

**Comment by nicolo-ribaudo** [comment]
Thank you for the bug report. I'm moving this to the main babel repository, since it is a bug with the code generator and not with the minifier itself.

@babel-bot Move to babel/babel
