### ISSUE TITLE
Add greenkeeper for top level devDependencies

### ISSUE THREAD

**Issue by hzoo** [babel/minify#74]
We added this in some of the other repos (@danez did)
- [ ] greenkeeper 
- [x] Also the top level "dependencies" should be devDeps? https://github.com/amasad/babel-minify/pull/75

After we release

**Comment by boopathi** [comment]
Closing this as inactive. Also the issue on greenkeeper for this support also seems inactive - https://github.com/greenkeeperio/greenkeeper/issues/139

**Comment by danez** [comment]
IF we still want this functionality we could look into https://renovateapp.com/ which is afaik the same as greenkeeper but with support for monorepos

**Comment by boopathi** [comment]
@danez nice. Didn't know about renovateapp. Thanks. I'll try it out. For now, I don't think we need this.
