### ISSUE TITLE
babel-plugin-minify-mangle-names renames variables in scope of eval 

### ISSUE THREAD

**Issue by jogibear9988** [babel/minify#749]
If I declare a Variable the Mangle Plugin renames them.

It does not work even if I set the "eval" option of the mangle plugin!

#### Input Code

```js
function test() {
	var data = "";
	return eval("data == null");
}
```

#### Actual Output

```js
function test(){var a="";return eval("data == null")}
```

#### Expected Output

```js
function test(){var data="";return eval("data == null")}
```

**Comment by jogibear9988** [comment]
If I use this:

```js
function test() {
	var data = "";
	return eval("return data == null");
}
```

also the "data" variable will not be kept, even if I use "var"

**Comment by jogibear9988** [comment]
shouldn't that https://github.com/babel/minify/blob/a7421897478e01cfddd62958c2ce2580ddf094e4/packages/babel-plugin-minify-mangle-names/src/index.js#L275 be "eval" instead of "!eval"

**Comment by boopathi** [comment]
Duplicate #366

**Comment by jogibear9988** [comment]
don‘t think it‘s the same, cause my is not about function parameters
