### ISSUE TITLE
Hoist Props

### ISSUE THREAD

**Issue by calebeby** [babel/minify#750]
Hi, I think it would be really cool if `babel-minify` could `hoist-props` like [uglify can](https://github.com/mishoo/UglifyJS2#compress-options).
#### Input Code

```js
const numbers = {
  one: 1,
  two: 2,
  three: 3
}

console.log(numbers.one)
```

#### Actual Output

```js
"use strict";var numbers={one:1,two:2,three:3};console.log(numbers.one);
```

#### Expected Output

```js
"use strict";console.log(1);
```

[Here's a demo](https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBGCuBbARgUwE4RgXhgbwCgYZxUAuGARgBoiYoB3ECgJluKgAt1VyYBmAgF8CBUJBAAbVADpJIAOYAKBCgwQZpAJRA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cbabili&prettier=false&targets=&version=6.26.0)

Thanks!

**Comment by boopathi** [comment]
Prior art: #344 
Duplicate #336
