### ISSUE TITLE
Add for loop optimizations to Array.forEach and for...of

### ISSUE THREAD

**Issue by SandHilt** [babel/minify#756]
#### Input Code

```js
let numbers = [1,2,3,4,5];

numbers.forEach((n) => console.dir(n));
```

#### Actual Output

```js
"use strict";

var numbers = [1, 2, 3, 4, 5];

numbers.forEach(function (n) {
  return console.dir(n);
});
```

#### Expected Output

```js
"use strict";

var numbers = [1, 2, 3, 4, 5];

for(let _i = 0; _i < numbers.length; ++_i){
  const n = numbers[_i];
  return console.dir(n);
}
```

#### Details
Array.forEach is more readable but more slower.
For...of is used interate over any interable object like Array, Map, Set, String, TypedArray, arguments and others.

And since the purpose of this preset is to write a shorter but more efficient code, I think it's worth discussing.

Explanation:
https://stackoverflow.com/a/43032526

jsperf tests:
https://jsperf.com/fast-array-foreach
https://jsperf.com/for-vs-foreach/293

**Comment by j-f1** [comment]
Your expected output is longer than the actual output, but babel-minify wants to shorten code.

**Comment by nicolo-ribaudo** [comment]
Also, the actual and the expected code do two different things. The second only logs `1`.

**Comment by boopathi** [comment]
I don't think minify should do this at all. Also babel-minify doesn't understand the program flow nor cross object/function boundary (for most cases) - `forEach` could mean anything.

```js
// global
const x = {
  forEach(foo) { return foo(42) }
}

function bar() {
  x.forEach(x => console.log(x));
}
```

I'm closing this as won't fix.
