### ISSUE TITLE
Drop Node 4?

### ISSUE THREAD

**Issue by boopathi** [babel/minify#766]
+ Jest 22 stops supporting node 4 - http://facebook.github.io/jest/blog/2017/12/18/jest-22.html
+ webpack drops node 4 support - eg. https://github.com/webpack-contrib/babel-minify-webpack-plugin/pull/70

**Comment by xtuc** [comment]
I think you'll be forced to since Babel dropped Node 4.

**Comment by boopathi** [comment]
Ah. yes. That makes it easier. Thanks. Closing this then. 

Decision: dropping node 4
