### ISSUE TITLE
Variable eliminated despite later use

### ISSUE THREAD

**Issue by Cyp** [babel/minify#774]
#### Input Code

```js
'use strict';
(() => {
  let myVariable;
  for (let i = 0; i < 1; ++i) {
    myVariable = 'Hello world!';
  }
  alert(myVariable);
})();
```

#### Actual Output

```js
'use strict';(function(){for(var b=0;1>b;++b){}alert(a)})();
```

Note `a` undefined, should be `'Hello world!'`.

#### Expected Output

```js
'use strict';(function(){for(var a,b=0;1>b;++b)a='Hello world!';alert(a)})();
```

#### Ideal Output

```js
'use strict';alert('Hello world!');
```

#### Details

http://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=OQVwzgpgBGAuBOBLAxrYBuAUACmwSigF4A-KAb0yigBsJYoBbATwDUBDJNgI1qyoDMA9vCjZa9RESgAGdFEkAeKAEY5AajWICFKlWbtOPaISjAAEhGrVBUAO7DqAEwCEGSlAC-7trXixs-hyI3LR4WB54-FhAA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cbabili&prettier=false&targets=&version=6.26.0

Gives `a is not defined`.

**Comment by boopathi** [comment]
This is already fixed in master. To try it out you can get the canary version of babel-minify from npm - https://github.com/babel/minify/tree/master/docs#canary-version
