### ISSUE TITLE
The 6.8.5 release of babel-plugin-transform-remove-console does not include the `exclude` option that is documented.

### ISSUE THREAD

**Issue by jdalton** [babel/minify#776]
The [6.8.5 release](https://github.com/babel/minify/blob/babel-plugin-transform-remove-console%406.8.5/packages/babel-plugin-transform-remove-console/src/index.js) of `babel-plugin-transform-remove-console` *(latest stable from Apr 2017)* does not include the `exclude` option that [is documented](https://babeljs.io/docs/plugins/transform-remove-console/) from Sept 2017.

Could y'all please pump the release for it?

**Update:**

~~Someone published a temp package until then:
https://www.npmjs.com/package/babel-plugin-transform-remove-console-seb~~

**Comment by jdalton** [comment]
Could y'all pump the release for it?

**Comment by boopathi** [comment]
I was planning to release sooner with migration to babel-7. But it looks like Babel-7 migration is taking longer. Anyway, I'll publish the current master sometime soon - mostly tomorrow.

Aside: There is canary version on npm (auto-published) if you want to try - https://github.com/babel/minify/tree/master/docs#canary-version

**Comment by jdalton** [comment]
Excellent! `babel-plugin-transform-remove-console@canary` works great!

**Comment by jdalton** [comment]
Ah, `canary` errors in Node 4 (syntax)

**Comment by boopathi** [comment]
I forgot about that. Have to add Node4 back. Related https://github.com/babel/minify/pull/767#issuecomment-353271587 and #766

**Comment by boopathi** [comment]
[babel-minify@0.3.0](https://github.com/babel/minify/releases/tag/gulp-babel-minify%400.3.0)
