### ISSUE TITLE
Identifier x has already been declared

### ISSUE THREAD

**Issue by tommytroylin** [babel/minify#780]
*  no Error thrown during minification
*  env: webpack with latest babel-minfiy-webpack-plugin
*  conf: nothing special `new MinifyPlugin({}, { comments: false }),`

#### Input Code
![image](https://user-images.githubusercontent.com/3364271/34982910-c8774c62-fae6-11e7-8fdf-ace938185866.png)

#### Actual Output
![image](https://user-images.githubusercontent.com/3364271/34982883-b6f9d0ae-fae6-11e7-9689-786a74312fd0.png)

#### Detail
`let {workId} = runtime;` =>  `let {workId: r} = runtime;`
`var xxx` => `var r`

they both use same identifier `r` and `Identifier 'r' has already been declared` error thrown on runtime

I think this may relate to `var`'s scope. use `let` or `const` may solve this problem. (I'm not sure, no time to dig in)
but I can't change all of `vars` since it appears everywhere...

**Comment by boopathi** [comment]
Can you give the code from the surrounding block?

The input code is the minimal code text which when passed through the minifier reproduces the same bug that you're facing. From your input, I'm not able to figure out what went wrong.

**Comment by boopathi** [comment]
I checked if there was a problem with the following test case - 

```js
function foo() {
  var a = 1;
  if (x + a) {
    let b = 2;
    var c = 3;
    x = b + bar(b) + baz(c);
  }
  return bar(a) + qux(c);
}

// Output:

function foo() {
  var b = 1;
  if (x + b) {
    let c = 2;
    var a = 3;
    x = c + bar(c) + baz(a);
  }
  return bar(b) + qux(a);
}
```

It seems to work fine.

I'm going to close this issue as not-actionable. Please comment with more info to reopen this.

**Comment by tommytroylin** [comment]
@boopathi  sorry for the very late response. I'm busy recently.

the minimal reproduce input.js
```js
function foo() {
  { // this is needed, just create a scope, acturally it's an if statement
    let aaa = bar1;
    let bbb = bar2;
    let { ccc } = bbb;
    var ddd = bar3;
    var eee = ccc + '_';
  }
}
console.log(foo);
```
use command: `minify input.js  --outFile output.js`

output.js (prettiered)
```js
function foo() {
  {
    let a = bar1,
      b = bar2,
      { ccc: c } = b;
    var a = bar3, // ohps
      b = c + '_'; // ohps
  }
}
console.log(foo);
```
original
```js
function foo(){{let a=bar1,b=bar2,{ccc:c}=b;var a=bar3,b=c+'_'}}console.log(foo);
```

**Comment by jgoyvaerts** [comment]
Just ran in the same issue today, but it seems like this project is inactive/unmaintained.
