### ISSUE TITLE
minify-mangle-names causes collision in try-catch scope

### ISSUE THREAD

**Issue by Jamesernator** [babel/minify#781]
It seems that minify-mangle-names doesn't understand `catch (varName)` scopes well enough to rename variables in such a scope. It renames the `catch (varName)` to the same name as the first `let/const` declaration in the `catch` block.

#### Input Code

```js
try {
  bar()
} catch (_) {
  let errorMessage = 'Oh dear' + item;
  console.log(errorMessage)
}
```

#### Actual Output

```js
try {
  bar();
} catch (a) {
  let a = 'Oh dear' + item;
  console.log(a);
}
```

#### Expected Output

```js
try {
  bar();
} catch (a) {
  let b = 'Oh dear' + item;
  console.log(a);
}
```

#### Details

Plugins: `babel-minify-mangle-names@0.2.0` and nothing else.

Now running it with babel `6.26.0` it produces the broken output. Running it with `@babel/core@7.0.0-beta.37` at least fails with the error `TypeError: test.js: Duplicate declaration "b" (This is an error on an internal node. Probably an internal error.)`. So this is probably an issue with babel and not the plugin itself.

**Comment by boopathi** [comment]
This is already fixed in https://github.com/babel/babel/pull/5980

**Comment by j-f1** [comment]
@boopathi Is there an ETA for Babel 7 coming out of beta so people will be able to get the bug fixes in production?
