### ISSUE TITLE
does not work online page

### ISSUE THREAD

**Issue by da0ka** [babel/minify#793]
https://babeljs.io/repl

Failed to load resource: the server responded with a status of 404 ()
https://unpkg.com/codemirror@5.30.0/keymap/sublime.js
Failed to load resource: the server responded with a status of 404 ()
https://unpkg.com/codemirror@5.30.0/addon/comment/comment.js
Failed to load resource: the server responded with a status of 404 ()
https://unpkg.com/codemirror@5.30.0/addon/search/searchcursor.js
react-dom.production.min.js:23
TypeError: Cannot read property 'attach' of undefined(…)

**Comment by boopathi** [comment]
Closing this as not related to babel-minify. And the repl is working.
