### ISSUE TITLE
Documented options for source maps not recognised

### ISSUE THREAD

**Issue by ygoe** [babel/minify#794]
I can't find an official documentation for this, just some notes on the npm package page. But the options mentioned there don't work.

#### Input Code

```
babel-minify "test.js" --outFile "test.min.js" --inputSourceMap "test.js.map" --sourceMaps
```

#### Actual Output

```
Error: Invalid Options passed: inputSourceMap,sourceMaps
```

#### Details

Just installed it with npm, so it should be the latest version.

**Comment by vigneshshanmugam** [comment]
These options are default overrides set by babel minify to override babel options and not as user options. 
https://github.com/babel/minify/tree/master/packages/babel-minify#overrides

The list of babel minify options is preset [here]https://github.com/babel/minify/tree/master/packages/babel-preset-minify#options

**Comment by ygoe** [comment]
That doesn't solve my problem. Does it mean that babel can't work with source maps? That's pretty poor. But I haven't found any transpiler that can handle that. JavaScript seems a relatively immature programming language for complex systems.

**Comment by vigneshshanmugam** [comment]
What I meant above is that these options are not present in babel minify itself but exists on babel. So you can solve it by passing through babel cli

```js
babel "test.js" --outFile "test.min.js" --presets=babel-preset-minify --inputSourceMap "test.js.map" --sourceMaps
```

**Comment by ygoe** [comment]
That doesn't do anything at all. No output, no files written.

**Comment by ygoe** [comment]
Sorry, there's an issue with npm. It creates .cmd files and calling .cmd files inside a .cmd file makes it terminate after the first call. Now I've fixed that, but babel complains that it can't find the preset:

> Error: Couldn't find preset "babel-preset-minify" relative to directory "."
