### ISSUE TITLE
Minify removing if body where a function declaration happens

### ISSUE THREAD

**Issue by SpeedProg** [babel/minify#812]
#### Input Code

```js
if (typeof _$ == 'undefined') {
	function _$(elementId) { return document.getElementById(elementId); }
}
```

#### Actual Output

```js
if('undefined'==typeof _$){}
```

#### Expected Output

```js
'undefined'==typeof _$&&(_$=function(a){return document.getElementById(a)});
```

#### Details

You can try here [http://babeljs.io/repl/](http://babeljs.io/repl/).
babel: 2.26.0
babel-minify: 0.3.0
no preset plugins used
but if you use es2015 preset you get this
```js
'use strict';if('undefined'==typeof _$)var _$2=function(a){return document.getElementById(a)};
```
which is actually good for what you get from es2015 without minify.
(still not what I'd expect through)

While the es2017 and es2016 presets leave code as is and minify produce same result as no preset. (if with an empty body)

**Comment by boopathi** [comment]
Function declarations are hoisted to the block and not its function parent in strict mode. I'd not trust hoisting too much by using functions inside try/catch/finally or if/else etc... 

This following will THROW even if it doesn't pass through a minification step. 

```js
function condition() { return true; }

function foo() {
  "use strict";
  if (condition()) {
    bar(1); // can use here
    function bar(x) { console.log("bar", x); }
  }
  bar(2); // will throw here
}

foo();
```

Spec:

https://www.ecma-international.org/ecma-262/8.0/index.html#sec-block-level-function-declarations-web-legacy-compatibility-semantics
