### ISSUE TITLE
Loop variables gone wrong, babel-preset-minify@0.4.0 regression

### ISSUE THREAD

**Issue by Cyp** [babel/minify#832]
**Versions**
* `babel-preset-minify@0.3.0`: Expected output
* `babel-preset-minify@0.4.0`: Wrong output
* `babel-preset-minify@0.4.1`: Wrong output

**To Reproduce**

```js
'use strict';
var arr = [];
(() => {
	for (let i = 1; i <= 3; ++i) {
		arr.push(() => console.log(i));
	}
})();
arr.forEach(x => x());
```

**Actual and Expected Output**

Locally:
```js
/*Locally*/ 'use strict';var arr=[];(function(){for(var a    =function(a){arr.push(function(){return console.log(a)})},a=1;3>=b;++b)a    (a)})(),arr.forEach(function(a){return a()});
/*Online*/  'use strict';var arr=[];(function(){for(var _loop=function(a){arr.push(function(){return console.log(a)})}    ;3>=i;++i)_loop(1)})(),arr.forEach(function(a){return a()});
/*Expected*/'use strict';var arr=[];(function(){for(var a    =function(a){arr.push(function(){return console.log(a)})},b=1;3>=b;++b)a    (b)})(),arr.forEach(function(a){return a()});

/*Locally:  ReferenceError: b is not defined*/
/*Online:   ReferenceError: i is not defined*/
/*Expected: 1 2 3*/
```

There seem to be 2 things wrong:
* The loop variable is either not declared or declared with the wrong name.
* The wrong thing is passed to the loop function.

**Configuration**

```js
console.log(babel.transform(…, {presets: ['minify', 'env']}).code);
```
```json5
    {"babel-core": "^6.26.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-minify": "^0.4.1"}
```

**Additional context**

http://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=OQVwzgpgBGAuBOBLAxrYBuAUANwIbynwIF4oBtAXSwApqBKKYgPigG9MooAzAewOoA2EWFESMoARnSioAHlIBmaQGpliBu06ciAOgAO4ABa0GzQkPixq6ulk4BfTPbr0su3vACiuZMYAejCx-9LaYQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Clatest%2Cbabili&prettier=false&targets=&version=6.26.0&envVersion=

**Comment by shincysl** [comment]
same here. it's critical.

**Comment by Cyp** [comment]
Testing with different settings, it works with `{presets: [['minify', {mangle: false}], 'env']}` and fails with just `mangle: true` and everything else false.

**Comment by vigneshshanmugam** [comment]
This is happening because we upgraded to babel 7(https://github.com/babel/minify/pull/487) in > 0.4.x versions which is marked as a breaking change https://github.com/babel/minify/blob/master/CHANGELOG.md#boom-breaking-change

If you change babel version in your package.json, Things would work fine. 
```json
"@babel/core": "^7.0.0-beta.40"
```

The reason why babel-minify: 0.3.0 is working is because it is using babel 6. Hope this helps.

**Comment by Cyp** [comment]
I get the same issue with `"@babel/core": "^7.0.0-beta.46"` (and replacing `require('babel-core')` with `require('@babel/core')`) and with `"babel-core": 7.0.0-beta.3`.

**Comment by Cyp** [comment]
Thanks to the answer at #836, I finally got it working.

Installing `"@babel/core"` isn't enough, also needs `"@babel/preset-env"`, which can then be used as `console.log(require('@babel/core').transform('alert("hi")', {presets: ['minify', '@babel/preset-env']}).code);`.
