### ISSUE TITLE
minify-infinity not doing anything

### ISSUE THREAD

**Issue by Cyp** [babel/minify#839]
**Describe the bug**

The minify-infinity pass doesn't do anything.

**To Reproduce**

```js
const infinities = [Infinity, 1/0, true/false, !0/!1, true/(true/(true/false))];
const zeroes = [1/Infinity, 1/(1/0), false/true, !1/!0, true/(true/false)];
const justone = Infinity;
alert(Infinity);
```

**Actual Output**

```js
"use strict";var infinities=[Infinity,1/0,!0/!1,!0/!1,!0/0],zeroes=[1/Infinity,0,0,0,0],justone=Infinity;alert(Infinity);
```

**Expected Output**

```js
"use strict";var infinities=[1/0,1/0,1/0,1/0,1/0],zeroes=[0,0,0,0,0],justone=1/0;alert(1/0);
```

**Additional context**

It returns here, and therefore doesn't do the substitution:
```js
        if (path.isLVal() && !path.parentPath.isExpressionStatement()) {
          return;
        }
```
The `path.parentPath.type` is `"ArrayExpression"`, `"BinaryExpression"`, `"VariableDeclarator"` and `"CallExpression"`, respectively.

I couldn't find any documentation on what `.isExpressionStatement()` is actually supposed to do, so I don't know whether the bug is in minify-infinity or in babel itself.

**Comment by boopathi** [comment]
Looks like this regressed in #241 ...
