### ISSUE TITLE
Unused catch variable causes redeclared variables

### ISSUE THREAD

**Issue by AshleyScirra** [babel/minify#865]
**Describe the bug**

This is similar to issue #635 and reproduces again with 0.4.3. If the variable declared by a catch block is unused, the contents of the catch block can incorrectly re-declare variable names already used in the scope.

**To Reproduce**

```js
function test()
{
	const foo = getFoo();

	try {
		doStuff();
	}
	catch (err) {
		const baz = getBaz();
		baz.reportError();
	}

	useFoo(foo);
}
```

**Actual Output**

```js
function test() {
	const a = getFoo();

	try {
		doStuff();
	} catch (a) {  // declares 'a' a second time
		const a = getBaz();  // declares 'a' a third time
		a.reportError();
	}

	useFoo(a);
}
```

**Expected Output**

```js
function test() {
	const a = getFoo();

	try {
		doStuff();
	} catch (b) {  // note 'b'
		const c = getBaz();  // note 'c'
		c.reportError();
	}

	useFoo(a);
}
```
**Configuration**

How are you using babel-minify?

`babel-minify CLI`

babel-minify version: `0.4.3`

babel version : `6.26.3`

babel-minify-config:

**Possible solution**

The only workaround I can find is to reference both other variables inside the catch block, e.g.:

```js
function test()
{
	const foo = getFoo();

	try {
		doStuff();
	}
	catch (err) {
		// reference both 'foo' and 'err'
		console.log(foo, err);
		const baz = getBaz();
		baz.reportError();
	}

	useFoo(foo);
}
```

This correctly minifies as:

```js
function test() {
	const a = getFoo();

	try {
		doStuff();
	} catch (b) {
		console.log(a, b);

		const c = getBaz();
		c.reportError();
	}

	useFoo(a);
}
```

**Additional context**

**Comment by AshleyScirra** [comment]
Actually it just looks like #635 is not fixed. The original repro still causes the bug in 0.4.3.

**Comment by Cyp** [comment]
Try installing `@babel/core@7.0.0-beta.47`, `babel-core@bridge` and `babel-preset-env@7`, and it might work.

Then `foo` and `err` still get minified to the same thing, but that seems to work anyway and the rest looks right, so I'm not sure whether or not that part is a bug.

**Comment by boopathi** [comment]
It was a babel bug as mentioned in #635 and it is fixed in babel@7.
