### ISSUE TITLE
Incorrect minification, not returning a boolean

### ISSUE THREAD

**Issue by nachoab** [babel/minify#870]
This function always returns a Boolean:

```js
function example(obj) {
  if (!!obj.foo || obj.bar) {
    return true;
  }
  return false;
}
```

But not after minification, see it here:

https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABAUwB4EMC2AHANsgCjgCMArASkQG8AoRRGYRAgQhZNIDpg45EAffog6di6AE6Va9euORQQ4pFHEhkAbjqIAvlrkKliYOlwBnDTW1A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=babili&prettier=false&targets=&version=6.26.0&envVersion=

**Comment by Cyp** [comment]
Works for me using an unreleased babel-minify (a28b6b000a05934864db9aea70cef671ea79b167) and babel (a955efa3e3d52f3f9f51978969a390abafc2b444).

```js
"use strict";function example(a){return!(!a.foo&&!a.bar)}
```

Installing some or all of these packages might work:
```
babel-core@bridge
@babel/core@7.0.0-beta.47
babel-preset-env@next
babel-preset-minify@canary
```

**Comment by boopathi** [comment]
It works correctly when I test against master. I'll close the issue. Please comment to reopen if you still face the issue.
