### ISSUE TITLE
minify of production files generated by webpack does not work

### ISSUE THREAD

**Issue by DanielRuf** [babel/minify#876]
**Describe the bug**

Running minify on production builds generated by webpack does not work

**To Reproduce**

Minimal code to reproduce the bug

See https://github.com/zurb/foundation-sites/issues/11351

**Actual Output**

```
SyntaxError: unknown: Unexpected token (11407:0)

  11405 |       else
  11406 |               root["__FOUNDATION_EXTERNAL__"] = root["__FOUNDATION_EXTERNAL__"] || {}, root["__FOUNDATION_EXTERNAL__"]["foundation.util.box"] = factory(root["__FOUNDATION_EXTERNAL__"]["foundation.core"], root["__FOUNDATION_EXTERNAL__"]["foundation.core"]);
> 11407 | })(window, function(__WEBPACK_EXTERNAL_MODULE__foundation_core__, __WEBPACK_EXTERNAL_MODULE__foundation_core_utils__) {
        | ^
  11408 | return /******/ (function(modules) { // webpackBootstrap
  11409 | /******/      // The module cache
  11410 | /******/      var installedModules = {};
```

```js
```

**Expected Output**

```js
```

**Stack Trace**

If applicable,

```

```

**Configuration**

How are you using babel-minify?

```
  "scripts": {
    "minify": "minify ./public_html/js/site.js"
  },
```

`babel-minify CLI`

babel-minify version: `0.4.3`

babel version : `7.0.0-beta.49`

babel-minify-config:

```json5
{
  removeConsole: true,
  keepFnNames: true
}
```

babelrc:

```json5
{
  plugins: [],
  presets: []
}
```

**Possible solution**

**Additional context**

**Comment by trusktr** [comment]
Darn unhelpful `unknown` errors.

**Comment by boopathi** [comment]
I'm not sure if this is a babel-minify error. If it's a parse error, it might be a problem with how the file is generated/stitched. Please comment to reopen if you still think it's a babel-minify issue.
