### ISSUE TITLE
Some packages have missing dependencies

### ISSUE THREAD

**Issue by mgroenhoff** [babel/minify#884]
**Describe the bug**
* [babel-plugin-minify-guarded-expressions](https://github.com/babel/minify/blob/9939bca95c66021e05528bb3b0eada0bc595d4c5/packages/babel-plugin-minify-guarded-expressions/src/index.js#L2) is missing dependency `babel-helper-evaluate-path`
* [babel-plugin-minify-simplify](https://github.com/babel/minify/blob/9939bca95c66021e05528bb3b0eada0bc595d4c5/packages/babel-plugin-minify-simplify/src/helpers.js#L4) is missing dependency `babel-helper-evaluate-path`

These were the ones I ran into but there might be more.

**Comment by gilly3** [comment]
This issue seems to prevent the use of minify with [pnpm](https://pnpm.js.org/).

**Comment by ExE-Boss** [comment]
@gilly3 In the meantime, you can use the following `pnpmfile.js`:
```js
const utils = require("@pnpm/hook-utils");

/** @type {import("@pnpm/hook-utils").PnpmHooks} */
exports.hooks = {
	readPackage(packageJson, context) {
		const pkg = utils.createReadPackageUtils(packageJson, context);
		const dependencies = packageJson.dependencies || {};

		switch (packageJson.name) {
			case "babel-plugin-minify-guarded-expressions":
			case "babel-plugin-minify-simplify":
				if (!dependencies["babel-helper-evaluate-path"])
					pkg.setDependency("babel-helper-evaluate-path", "0.5.0");
				break;
		}

		pkg.logChanges();
		return packageJson;
	},
};
```
