### ISSUE TITLE
Object literals token error

### ISSUE THREAD

**Issue by seuai** [babel/minify#894]
chrome and nodejs package

**To Reproduce**

![image](https://user-images.githubusercontent.com/29100776/44072629-f76e9780-9fca-11e8-9b2d-e541083362f0.png)

**Babel option**
`
{
	minified : true,
	comments : false
};
`
minifying error

**Configuration**
Using these packages:

 `   "babel-core": "~6.26.3"`

**Comment by bardiharborow** [comment]
At the time of writing, [Spread Properties](https://github.com/tc39/proposal-object-rest-spread) is a [stage-4 proposal](https://tc39.github.io/process-document/) and has not yet been incorporated into a new version of the EMCAScript standard. For now, you need to enable the `stage-3` preset to use it (a request to move the plugin forwards has been made at babel/babel#7285).

**Comment by seuai** [comment]
There was a problem about five months ago, but now there is no problem.
