### ISSUE TITLE
babel-minify still relevant?

### ISSUE THREAD

**Issue by DanielRuf** [babel/minify#945]
Is babel-minify still relevant? Because terser is very good, and closure-compiler is still one of the best.

Additionally butternut is not actively developed and has several issues - for example the compression throws errors in projects.

**Comment by bardiharborow** [comment]
If you are asking whether there are more functional and more stable compression engines available, then you have answered your own question. This project's tight integration with Babel however makes it a promising candidate if more development time is invested. Whether this will happen or not... well trying to divine the open-source crystal ball is a pointless endeavor.

**Comment by xtuc** [comment]
Keep in mind that babel-minify is marked as beta currently.

**Comment by DanielRuf** [comment]
Okay, thanks for the info and clarification.
This answers my question(s).

**Comment by hzoo** [comment]
Going to write up something for this in a bit (and I'll update the readme to be more clear). I think @bardiharborow has it correct: the general idea makes sense so I don't think we would want to drop it, but currently there isn't enough people working on it so we should just signal that better.
